import type { IconProps as PhosphorIconProps } from '@phosphor-icons/react';
import {
  AppleLogoIcon,
  ArrowCounterClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BellIcon,
  BowlFoodIcon,
  CaretDownIcon,
  CaretRightIcon,
  ChartBarIcon,
  ChartLineDownIcon,
  ChartLineUpIcon,
  ChartPieSliceIcon,
  ChatCircleDotsIcon,
  CheckIcon,
  CheckCircleIcon,
  CherriesIcon,
  CircleIcon,
  CircleNotchIcon,
  CirclesThreeIcon,
  ClockIcon,
  ClockCountdownIcon,
  CookingPotIcon,
  CreditCardIcon,
  CurrencyDollarIcon,
  DotsThreeOutlineIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  FacebookLogoIcon,
  FireIcon,
  FlaskIcon,
  ForkKnifeIcon,
  GearIcon,
  GiftIcon,
  GoogleLogoIcon,
  GrainsIcon,
  HandshakeIcon,
  HeadsetIcon,
  HeartIcon,
  HouseIcon,
  HouseLineIcon,
  InfoIcon,
  InstagramLogoIcon,
  LeafIcon,
  LinkedinLogoIcon,
  ListIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapPinLineIcon,
  MapTrifoldIcon,
  MinusIcon,
  MopedIcon,
  PackageIcon,
  PaperPlaneTiltIcon,
  PencilSimpleIcon,
  PhoneIcon,
  PlantIcon,
  PlusIcon,
  PlusCircleIcon,
  ReceiptIcon,
  ScalesIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  ShoppingCartSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StorefrontIcon,
  TagIcon,
  TrashIcon,
  TruckIcon,
  UserIcon,
  UserCircleIcon,
  UsersIcon,
  WarningIcon,
  WarningCircleIcon,
  XIcon,
} from '@phosphor-icons/react';
import type { ComponentType } from 'react';

/**
 * The icons this product uses, keyed by the same kebab-case name the mockup writes in its
 * CSS classes.
 *
 * Named imports rather than `import * as Phosphor`: the namespace import defeats
 * tree-shaking and drags all ~9,000 Phosphor components into the bundle, which measured at
 * 1.1 MB gzip against a 250 KB budget. Adding an icon is one line here.
 */
export const ICON_REGISTRY = {
  'apple-logo': AppleLogoIcon,
  'arrow-counter-clockwise': ArrowCounterClockwiseIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  bell: BellIcon,
  'bowl-food': BowlFoodIcon,
  'caret-down': CaretDownIcon,
  'caret-right': CaretRightIcon,
  'chart-bar': ChartBarIcon,
  'chart-line-down': ChartLineDownIcon,
  'chart-line-up': ChartLineUpIcon,
  'chart-pie-slice': ChartPieSliceIcon,
  'chat-circle-dots': ChatCircleDotsIcon,
  check: CheckIcon,
  'check-circle': CheckCircleIcon,
  cherries: CherriesIcon,
  circle: CircleIcon,
  'circle-notch': CircleNotchIcon,
  'circles-three': CirclesThreeIcon,
  clock: ClockIcon,
  'clock-countdown': ClockCountdownIcon,
  'cooking-pot': CookingPotIcon,
  'credit-card': CreditCardIcon,
  'currency-dollar': CurrencyDollarIcon,
  'dots-three-outline': DotsThreeOutlineIcon,
  'envelope-simple': EnvelopeSimpleIcon,
  eye: EyeIcon,
  'facebook-logo': FacebookLogoIcon,
  fire: FireIcon,
  flask: FlaskIcon,
  'fork-knife': ForkKnifeIcon,
  gear: GearIcon,
  gift: GiftIcon,
  'google-logo': GoogleLogoIcon,
  grains: GrainsIcon,
  handshake: HandshakeIcon,
  headset: HeadsetIcon,
  heart: HeartIcon,
  house: HouseIcon,
  'house-line': HouseLineIcon,
  info: InfoIcon,
  'instagram-logo': InstagramLogoIcon,
  leaf: LeafIcon,
  'linkedin-logo': LinkedinLogoIcon,
  list: ListIcon,
  'lock-simple': LockSimpleIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  'map-pin': MapPinIcon,
  'map-pin-line': MapPinLineIcon,
  'map-trifold': MapTrifoldIcon,
  minus: MinusIcon,
  moped: MopedIcon,
  package: PackageIcon,
  'paper-plane-tilt': PaperPlaneTiltIcon,
  'pencil-simple': PencilSimpleIcon,
  phone: PhoneIcon,
  plant: PlantIcon,
  plus: PlusIcon,
  'plus-circle': PlusCircleIcon,
  receipt: ReceiptIcon,
  scales: ScalesIcon,
  'shield-check': ShieldCheckIcon,
  'shopping-bag': ShoppingBagIcon,
  'shopping-cart': ShoppingCartIcon,
  'shopping-cart-simple': ShoppingCartSimpleIcon,
  'sign-out': SignOutIcon,
  'sliders-horizontal': SlidersHorizontalIcon,
  'squares-four': SquaresFourIcon,
  stack: StackIcon,
  star: StarIcon,
  storefront: StorefrontIcon,
  tag: TagIcon,
  trash: TrashIcon,
  truck: TruckIcon,
  user: UserIcon,
  'user-circle': UserCircleIcon,
  users: UsersIcon,
  warning: WarningIcon,
  'warning-circle': WarningCircleIcon,
  x: XIcon,
} as const satisfies Record<string, ComponentType<PhosphorIconProps>>;

export type IconName = keyof typeof ICON_REGISTRY;

/**
 * Narrows a string from the database to an icon this build actually ships.
 *
 * Product and category rows store a Phosphor name chosen by an editor, and the registry is
 * deliberately a closed list (decision D-10) - a namespace import measured 1.1 MB gzip. So a
 * name that is not in it renders nothing, and every caller needs a fallback rather than a
 * blank space.
 */
export function isIconName(value: string | null | undefined): value is IconName {
  return value !== null && value !== undefined && Object.hasOwn(ICON_REGISTRY, value);
}
