import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

/**
 * Reads `docs/design/catalog.json` at run time rather than importing it.
 *
 * The file is generated by `scripts/extract-design-data.mjs` from the prototype and lives
 * outside `apps/api`, so importing it would drag a path outside the package's root into the
 * TypeScript program and into the production bundle. Reading and validating it here keeps the
 * seed the only thing that depends on it, and the schema below fails loudly if a future
 * handoff changes the shape - which is the whole point of regenerating the file per handoff.
 */

const Weight = z.object({ label: z.string(), price: z.number().positive() });

const DesignProduct = z.object({
  slug: z.string(),
  name: z.string(),
  cat: z.string(),
  catKey: z.string(),
  origin: z.string(),
  region: z.string(),
  badges: z.array(z.string()),
  stock: z.enum(['in', 'low', 'out']),
  defWeight: z.string(),
  tone: z.string(),
  icon: z.string(),
  blurb: z.string(),
  desc: z.string(),
  weights: z.array(Weight).min(1),
  imageUrl: z.string().url().nullable(),
});

const DesignCategory = z.object({
  key: z.string(),
  label: z.string(),
  count: z.number().int(),
  icon: z.string(),
});

const DesignRecipe = z.object({
  title: z.string(),
  time: z.string(),
  level: z.string(),
  cat: z.string(),
  img: z.string().url(),
  blurb: z.string(),
});

const DesignFaq = z.object({ q: z.string(), a: z.string() });

const DesignWholesale = z.object({
  date: z.string(),
  biz: z.string(),
  type: z.string(),
  vol: z.string(),
  prod: z.string(),
  status: z.string(),
});

const DesignOrder = z.object({
  no: z.string(),
  date: z.string(),
  cust: z.string(),
  items: z.string(),
  total: z.string(),
  status: z.string(),
});

const Catalog = z.object({
  categories: z.array(DesignCategory).min(1),
  products: z.array(DesignProduct).min(1),
  recipes: z.array(DesignRecipe).min(1),
  faqs: z.array(DesignFaq).min(1),
  wholesaleRequests: z.array(DesignWholesale).min(1),
  demoOrders: z.array(DesignOrder).min(1),
});

export type DesignCatalog = z.infer<typeof Catalog>;
export type DesignProduct = z.infer<typeof DesignProduct>;

const CATALOG_PATH = fileURLToPath(
  new URL('../../../../../docs/design/catalog.json', import.meta.url),
);

export function loadDesignCatalog(): DesignCatalog {
  const raw: unknown = JSON.parse(readFileSync(CATALOG_PATH, 'utf8'));
  const parsed = Catalog.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `docs/design/catalog.json does not match the expected shape. Re-run ` +
        `scripts/extract-design-data.mjs, then reconcile:\n${parsed.error.issues
          .map((issue) => `  ${issue.path.join('.')}: ${issue.message}`)
          .join('\n')}`,
    );
  }
  return parsed.data;
}
